### PR TITLE
Mixed precision support + setup cleanup and code refactoring

### PR DESCRIPTION
**Pull request by andreped**
This PR is related to issue https://github.com/awsaf49/gcvit-tf/issues/7.

I also modified the original gist, demonstrating that these changes resolves the issue, see [here](https://colab.research.google.com/gist/andreped/05ad0d6802e3ca0242dd287288a24fb9/gcvit-mixed-precision-fix.ipynb).

#### Changes:
* Added mixed precision support
* Moved requirements stuff inside `setup.py` + removed `gradio` as not part of python module
* Swapped custom `Identity` layer implementation with built-in `tf.keras.layers.Identity` which do the same
* Added mixed precision test to `tests/`
* Fixed code style inconsistencies - follow most commonly used standard, IMO

---
#### Future work:
* `gradio` as it is only used for the demo `app.py`, I would install it seperately in a Jupyter Notebook, if you wish to demonstrate it. Having it included inside the package is just bloatware. Unless you wish to make it a CLI and bundle it as part of the package.

* matplotlib is only used for a single _cmap_ in the GradCAM implementation. Matplotlib introduces an annoying GPL license which corrupts the MIT license. Perhaps make a simple numpy implementation instead?

* tf-addons is sunset, AFAIK, but is only used for a single custom layer. Perhaps move that layer inside this project and remove `tf-addons`.

If of interest, I could attempt give a crack at it. Always fun to contribute to cool projects :] However, it is more natural to make seperate PRs to address these issues.

### CODE REVIEW

**Comment by awsaf49** [comment]
Thank you for your PR. I appreciate your contribution. I will review it after 29/04/2023. Please bear with me as I am currently occupied with another task.

**Comment by andreped** [comment]
> Please bear with me as I am currently occupied with another task.

No worries.

**Comment by awsaf49** [comment]
@andreped 
* Could you create a separate PR for code refactoring and leave this one for mixed precision? Also for code formatting use [Keras style](https://github.com/keras-team/keras/blob/master/shell/format.sh). 
* Regarding `tf.keras.layers.Identity` I was aware of this update but I was hesitant as it is only supported in `> TF 2.11` so this library will break for the older version of TF.

**Comment by andreped** [comment]
Probably just easier to make a separate PR and close this one then. Will make a PR with only the mixed precision-related fix.

**Comment by andreped** [comment]
> Yes, that works too. Sorry for the trouble

No worries. I made the new PR now.

**Comment by awsaf49** [comment]
@andreped will you be able to create a pr on formatting? It's okay if you are not willing then I can do it by myself

**Comment by andreped** [comment]
> @andreped will you be able to create a pr on formatting? It's okay if you are not willing then I can do it by myself

Oh, I did not see it as that critical, so I only made the PR for mixed precision.

I can setup some flake8 linting CI with Keras as reference. Any preferences?

**Pull request closed without merging**
